spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    hibernate:
      ddl-auto: update
    show-sql: true

